# Importuojam numpy

In [1]:
import numpy as np

# Pagrindai

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Kiek dimensijų
a.ndim

1

In [5]:
# Kokia figūra
b.shape

(2, 3)

In [6]:
# Koks duomenų tipas
a.dtype

dtype('int32')

In [7]:
# Koks vieno elemento dydis baitais
a.itemsize

4

In [8]:
# Koks pilnas viso masyvo dydis baitais
a.nbytes

12

In [9]:
# Kiek masyve elementų
a.size

3

# Gauname informaciją, pakeičiame norimus elementus

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Gauti konkrečią reikšmę [r, c]
a[1, 5]

13

In [12]:
# Gauti konkrečią eilę
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Gauti konkretų stulpelį
a[:, 2]

array([ 3, 10])

In [14]:
# Gauti pagal indeksus ir žingsnius [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [16]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [17]:
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3d pavyzdys

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Gauti konkretų elementą
b[0,1,1]

4

In [20]:
# Pakeisti 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [21]:
# Pakeisti 
b[:,1,:] = [[9,9,9],[8,8]]
b

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Sukuriame skirtingų tipų sąrašus/masyvus

In [ ]:
# Generuojam masyvą kur visi skaičiai yra 0
np.zeros(5)

In [ ]:
np.zeros((2,3))

In [ ]:
# Masyvas kur visi skaičiai yra 1 ir duomenų tipas yra int32
np.ones((4,2,2), dtype='int32')

In [ ]:
# Įstatom bet kokį kitą skaičių
np.full((2,2), 99)

In [ ]:
# Sustatom skaičius kito masyvo pagrindų (full_like)
np.full_like(a, 4)

In [ ]:
# Galima ir taip
np.full(a.shape, 4)

In [ ]:
# Atsitiktiniai float skaičiai
np.random.rand(4,2)

In [ ]:
# Atsitiktiniai float skaičiai, daugiau dimensijų
np.random.rand(4,2,3)

In [ ]:
# Atsitiktiniai float skaičiai, pagal kito sąrašo struktūrą
np.random.random_sample(a.shape)

In [ ]:
# Atsitiktiniai int skaičiai, [0-7) rėžiuose
np.random.randint(7, size=(3,3))

In [ ]:
# Atsitiktiniai int skaičiai, [-4,8) rėžiuose
np.random.randint(-4,8, size=(3,3))

In [ ]:
# Identity matrica
np.identity(5)

In [ ]:
# Masyvo pakartojimas
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

In [ ]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

In [ ]:
output[1:-1,1:-1] = z
print(output)

# Matematika

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
np.cos(a)

In [ ]:
np.sin(a)

Skaityti daugiau: https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Tiesinė algebra

In [ ]:
a = np.ones((2,3))
print(a)

In [ ]:
b = np.full((3,2), 2)
print(b)

In [ ]:
np.matmul(a,b)

In [ ]:
# Surasti determinantą
c = np.identity(3)
np.linalg.det(c)

Skaityti daugiau: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

# Statistika

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats)

In [ ]:
np.max(stats, axis=0)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats)

In [ ]:
np.sum(stats, axis=0)

# Sąrašų/masyvų pertvarkymas

Figūros pakeitimas

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

In [ ]:
before.reshape((8,1))

In [ ]:
before.reshape((4,2))

In [ ]:
before.reshape((2,2,2))

In [ ]:
before.reshape((2,3))

Masyvų sujungimas

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [ ]:
np.vstack([v1,v2])

In [ ]:
np.vstack([v1,v2,v2,v2])

In [ ]:
np.vstack([v1,v2,v1,v2])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [ ]:
np.hstack((h1,h2))

# Įvairūs kiti dalykai

## Duomenų užkrovimas iš failo

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

## Boolean kaukės (boolean masking) ir pažengęs indeksavimas (advanced indexing)

In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
# Galima indeksuoti su sąrašu su numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

In [ ]:
np.any(filedata > 50, axis=0) # stulpeliai

In [ ]:
np.all(filedata > 50, axis=0) # stulpeliai

In [ ]:
np.all(filedata > 50, axis=1) # eilutės

In [ ]:
((filedata > 50) & (filedata < 100))

In [ ]:
(~((filedata > 50) & (filedata < 100))) # atvirkščiai, nepatenka